-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.


CREATE DATABASE CLIENTES_5

USE CLIENTES_5

CREATE TABLE CLIENTES
(
    ID_CLIENTE INT CONSTRAINT PK_CLIENTES PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL
)

CREATE TABLE PRODUTOS
(
    ID_PRODUTO INT CONSTRAINT PK_PRODUTOS PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    QUANTIDADE INT NOT NULL
)

CREATE TABLE PEDIDOS
(
    ID_PEDIDO INT CONSTRAINT PK_PEDIDOS PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    DATA_ENTREGA DATE NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
)

SELECT * FROM CLIENTES
SELECT * FROM PRODUTOS
SELECT * FROM PEDIDOS

INSERT CLIENTES (ID_CLIENTE,NOME,CPF,ENDERECO,CIDADE,TELEFONE) VALUES (1, 'JOAO', '12345678901', 'PIRIRI', 'GUARACITY', '123456789')
INSERT CLIENTES (ID_CLIENTE,NOME,CPF,ENDERECO,CIDADE,TELEFONE) VALUES (2, 'MARIA', '12345678902', 'PORORO', 'JARAS', '123456789')
INSERT PRODUTOS (ID_PRODUTO,NOME,DESCRICAO,PRECO,QUANTIDADE) VALUES (1, 'ARROZ', 'ARROZ BRANCO', 10.00, 100)
INSERT PRODUTOS (ID_PRODUTO,NOME,DESCRICAO,PRECO,QUANTIDADE) VALUES (2, 'FEIJAO', 'FEIJAO PRETO', 10.00, 100)
INSERT PEDIDOS (ID_PEDIDO,ID_CLIENTE,ID_PRODUTO,DATA_PEDIDO,DATA_ENTREGA) VALUES (1, 1, 1, '2021-02-02', '2021-02-03')
INSERT PEDIDOS (ID_PEDIDO,ID_CLIENTE,ID_PRODUTO,DATA_PEDIDO,DATA_ENTREGA) VALUES (2, 2, 2, '2021-02-02', '2021-02-03')



SELECT * FROM CLIENTES
SELECT * FROM PRODUTOS
SELECT * FROM PEDIDOS

UPDATE CLIENTES SET NOME = 'JOAO DA UNIVILLE' WHERE ID_CLIENTE = 1

