


CREATE DATABASE AULA29092a

USE AULA29092a

CREATE TABLE FUNCIONARIOS
(FUNCIONARIOCODIGO INT
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,
FUNCIONARIONOME CHAR(20))

CREATE TABLE DEPENDENTES
(
    DEPEDENTECODIGO INT,
    DEPENDENTENOME CHAR(20),
    FUNCIONARIOCODIGO INT
)

ALTER TABLE DEPENDENTES
ADD CONSTRAINT FK_DEPENDENTES_FUNCIONARIO
FOREIGN KEY (FUNCIONARIOCODIGO)
REFERENCES FUNCIONARIOS(FUNCIONARIOCODIGO)

INSERT DEPENDENTES (DEPEDENTECODIGO,DEPENDENTENOME,FUNCIONARIOCODIGO)
VALUES (123,'FILHO DO DORNEL', 1322547)


INSERT FUNCIONARIOS 
(FUNCIONARIOCODIGO, FUNCIONARIOCODIGO)
VALUES (132456,'DORNEL')3


ALTER TABLE FUNCIONARIOS
ADD DATAADIMISSAO DATE