


CREATE DATABASE AULA29092a

USE AULA29092a

CREATE TABLE FUNCIONARIOS
(FUNCIONARIOCODIGO INT
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,
FUNCIONARIONOME CHAR(20))

CREATE TABLE DEPENDENTES
(
    DEPEDENTECODIGO INT,
    DEPENDENTENOME CHAR(20),
    FUNCIONARIOCODIGO INT
)

ALTER TABLE DEPENDENTES
ADD CONSTRAINT FK_DEPENDENTES_FUNCIONARIO
FOREIGN KEY (FUNCIONARIOCODIGO)
REFERENCES FUNCIONARIOS(FUNCIONARIOCODIGO)

INSERT FUNCIONARIOS (FUNCIONARIOCODIGO, FUNCIONARIOCODIGO)
VALUES (132456, 'DORNEL')