



CREATE TABLE FUNCIONARIOS 
(
    COD_FUNCIONARIO INT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(50),
)

INSERT FUNCIONARIOS (COD_FUNCIONARIO, NOME_FUNCIONARIO) VALUES (1, 'JOAO')

CREATE TABLE DEPENDENTES 
(
    COD_DEPENDENTE INT PRIMARY KEY,
    NOME_DEPENDENTE VARCHAR(50),
    COD_FUNCIONARIO INT
    CONSTRAINT FK_FUNCIONARIO_DEP FOREIGN KEY (COD_FUNCIONARIO)
    REFERENCES FUNCIONARIOS(COD_FUNCIONARIO)
)

INSERT DEPENDENTES (COD_DEPENDENTE, NOME_DEPENDENTE, COD_FUNCIONARIO)
VALUES (1, 'MARIA', 1)

SELECT * FROM DEPENDENTES
SELECT * FROM FUNCIONARIOS
DELETE FROM FUNCIONARIOS
WHERE COD_FUNCIONARIO = 1