CREATE DATABASE AULA040102022_3

USE AULA040102022_3

CREATE TABLE PESSOAS
(
    PESSOASCOD INT CONSTRAINT PK_PESSOAS PRIMARY KEY,
    PESSOASNOME CHAR(50) NOT NULL,
    PESSOASDTNASC DATETIME NULL,
    PESSOASAL MONEY
)

INSERT PESSOAS (PESSOASCOD,PESSOASNOME,PESSOASDTNASC,PESSOASAL)
VALUES (2,'JOAO','2004-23-02',1000)


INSERT PESSOAS
VALUES (3,'2000-23-08')


INSERT PESSOAS SELECT * FROM PESSOAS WHERE PESSOASCOD = 1

SELECT * FROM PESSOAS


UPDATE PESSOAS
    SET PESSOASNOME = 'PEDRO',
        PESSOASDTNASC = '2000-23-05',
        PESSOASAL = 2000
    WHERE PESSOASCOD = 1 AND PESSOASNOME = ''